spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    open-in-view: false # (2.5~) Lazy Loading을 위해 Open Session in View 사용 안함

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace